### ISSUE TITLE
Any plan for XPath 2.0

### ISSUE THREAD

**Issue by suntong** [ChrisTrenkamp/xsel#1]
First of all, bravo on your new polished `xsel` @ChrisTrenkamp! 

Now, 

> xsel is a library that implements the XPath **1.0** specification. 

Any plan for XPath 2.0? since 

> XML tropes such as namespaces and processing instructions are defined in the package

Basically all XML files that I'm dealing with are XPath *2.0* ones, with all sorts of weird namespaces.

**Comment by ChrisTrenkamp** [comment]
No, it will be XPath 1.0 only.
